### PR TITLE
`package-lock.json`

### PR DESCRIPTION
**Pull request by brettz9**
- npm: Update devDeps
- npm: Add `package-lock.json`
- Linting: Fixes for newly-enforced (indentation) ESLint rules

(Changes as discussed in #234)

### CODE REVIEW

**Comment by brettz9** [comment]
1. It get the error when switching nvm to Node v10.0.0 but there is no issue on the 9.2.1 I was using. As I'm not as familiar with that part of the code, I'd appreciate it if someone else could take a look. I wonder if Node 10.0 could be adding its own named capture and there is some kind of conflict there. 
2. I've changed to add as a separate commit (but within the same PR).

**Comment by brettz9** [comment]
Btw, `master` is failing with the same test using Node 10.0.0

**Comment by josephfrazier** [comment]
Hmm, sure enough, it does: https://travis-ci.org/slevithan/xregexp/builds/370310563

I think we should pin Travis to Node v9 for now, and figure out the v10 issue separately later. I'll make a PR for that.

**Comment by josephfrazier** [comment]
I just merged https://github.com/slevithan/xregexp/pull/242, so feel free to rebase this branch onto master

**Comment by brettz9** [comment]
I've rebased but there is a build problem which I'm investigating...

**Comment by brettz9** [comment]
Sorry for the last comment (just deleted)--no problems in this PR so feel free to merge if ok...

**Comment by josephfrazier** [comment]
Thanks, it looks great!

**Pull request merged**
