### PR TITLE
More web-compatible way to feature-test for sticky RegExp support

### PR DESCRIPTION
**Pull request by vp2177**
This is to work around https://bugs.chromium.org/p/v8/issues/detail?id=4617

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Thanks, @vp2177!

This is the same issue as https://github.com/slevithan/xregexp/commit/d93af4324e9384e457fb954eb1771520ba4654e5#commitcomment-13230259 (ref. #102, #121). Sorry for not spotting this particular instance before the v3 release :(

In case we want to avoid `hasOwnProperty`, the `try`-`catch` approach we’ve used before can be used.

**Comment by vp2177** [comment]
The issue I see with `try-catch` is, in the latest V8 `RegExp.prototype.sticky` would throw, but that doesn't mean it's not supported (it is!).

**Comment by mathiasbynens** [comment]
@vp2177 I meant like this: https://github.com/slevithan/xregexp/pull/102/files#diff-45ba574373e64db1c6c2653734c6e319R59

**Comment by mathiasbynens** [comment]
Alternatively, to avoid both `RegExp.prototype` and `try`/`catch`:

```js
var emptyRegExp = /(?:)/;

var supportsSticky = 'sticky' in emptyRegExp;
var supportsUnicode = 'unicode' in emptyRegExp;
```

**Comment by mathiasbynens** [comment]
Wait a second… This issue was fixed in #102 already, and XRegExp v3 includes this fix. This patch only changes the old versioned copies of XRegExp in the `test/perf` folder, which doesn’t really make sense.

If you see someone using an old version of XRegExp, please point them here and ask them to update to v3.

**Comment by mathiasbynens** [comment]
old comments removed to avoid confusion

**Pull request closed without merging**
