### PR TITLE
bower.json

### PR DESCRIPTION
**Pull request by tomascassidy**
Add bower.json to support bower.io

Most fields were copied from package.json but wasn't sure what to add for ```dependencies``` and ```devDependencies```.  Explanation for what to put in those fields is at http://bower.io/docs/creating-packages/

You will also need to register the XRegExp package with bower once bower.json has been added, using the instructions provided at the above link.

#63 #78

### CODE REVIEW

**Comment by listepo** [comment]
+1

**Comment by slevithan** [comment]
Planning to add this shortly and register with bower, hopefully this weekend. First want to read the above referenced doc and play with Bower a bit. Thanks, @tomascassidy!

**Comment by slevithan** [comment]
I've registered `xregexp` with Bower. @tomascassidy and @listepo do things seem to be working as expected? I have not used Bower previously.

**Comment by tomascassidy** [comment]
I tried installing ```xregexp``` with bower in a new empty directory, with default options for ```bower init```, but it appears to be ignoring the ```ignore``` option in bower.json.  I'm still seeing all the files in the repo get installed despite them appearing in the ```ignore``` section.  Can you verify this?  I'm not an export on bower so not really sure what's going on here.  Don't worry too much if it can't be fixed up.

**Comment by slevithan** [comment]
That makes sense actually. Since I didn't know how Bower worked, I screwed up by not merging your `bower.json` until after publishing the `v3.0.0` git tag. :-( And because the latest tag does not contain a `bower.json`, it's not ignoring the `ignore` section; rather there's no `bower.json` to follow despite the project now being registered with Bower. This will be fixed as soon as I publish a new semver git tag.

In order to address this sooner, I'll publish a `v3.0.1` tag as soon as I fix a bug or two.

**Comment by tomascassidy** [comment]
Thanks.  That looks like it should fix what I was seeing.

**Comment by Goddak** [comment]
@slevithan do you have an ETA on when you're able to publish a new semver? I'm relying on a couple of properties added in the `bower.json` in d0e665d4068cec4d15919215b098b2373f1f12e9 for my build tooling.

**Comment by slevithan** [comment]
@Goddak I've been slower on this than I expected, but I'm planning to publish an update within the next couple weeks.

**Comment by Goddak** [comment]
+1 @slevithan

**Comment by slevithan** [comment]
v3.1.0 was released today. :dancer:

**Pull request merged**
