### PR TITLE
Add test script

### PR DESCRIPTION
**Pull request by josephfrazier**
This makes it easier for new developers to run the tests, by typing `npm
test`. This will build `xregexp-all.js`, then open `tests/index.html` in a
browser, using [opener].

[opener]: https://www.npmjs.com/package/opener

### CODE REVIEW

**Comment by josephfrazier** [comment]
Alternatively, if you'd rather have the tests run in Node without needing to open a browser, I can update this PR to do that instead.

**Comment by slevithan** [comment]
No preference, personally. I'm happy to merge this as is. But if you felt strongly about running the tests in Node instead I'd be happy to merge that over this. :)

**Comment by josephfrazier** [comment]
Thanks for the merge! I've just opened https://github.com/slevithan/xregexp/pull/159 to get the tests running in Node. This makes the workflow a little smoother (in my opinion), and makes it possible to use an automated CI tool like [Travis](https://travis-ci.org/) (would you be interested in that?).

**Comment by slevithan** [comment]
Yes, I'd be interested. Have never set it up before though.

**Pull request merged**
