### PR TITLE
Upgrade to @babel/runtime-corejs3

### PR DESCRIPTION
**Pull request by josephfrazier**
Fixes https://github.com/slevithan/xregexp/issues/279

### CODE REVIEW

**Comment by slevithan** [comment]
@josephfrazier, do you know why the failure? Feel free to go ahead and land build or other improvements, and/or publish new tags/releases, without review.

**Comment by josephfrazier** [comment]
Hmm, not sure. Here's the error, for reference:

```
> browserify lib/index.js --standalone XRegExp > xregexp-all.js
Error: Cannot find module '@babel/runtime-corejs2/helpers/interopRequireDefault' from '/home/travis/build/slevithan/xregexp/lib'
    at /home/travis/build/slevithan/xregexp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/travis/build/slevithan/xregexp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/travis/build/slevithan/xregexp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/travis/build/slevithan/xregexp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/travis/build/slevithan/xregexp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/travis/build/slevithan/xregexp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:170:21)
```

I'll see if I can figure it out.

> Feel free to go ahead and land build or other improvements, and/or publish new tags/releases, without review

Thanks! I'll have to remember the entire release process, but I think we have it written down in an issue/PR somewhere.

**Comment by josephfrazier** [comment]
Though, it looks like I don't have permission to publish on NPM, so I'll still have to ask you to do that, unless you want to add me as an owner.

**Comment by slevithan** [comment]
@josephfrazier 

Here’s the list of steps: <https://github.com/slevithan/xregexp/pull/205#issuecomment-354236652>.

I’ve also just added you as an `xregexp` npm maintainer via npmjs.com.

Thanks for all your help with this!

**Comment by tdjastrzebski** [comment]
Will the new version 4.2.x be published on npmjs.com?

**Comment by humphreyn** [comment]
@josephfrazier  & @slevithan ,
Great work guys. Hopefully as @tdjastrzebski asked you will be publishing this new version on NPM soon

**Comment by josephfrazier** [comment]
Thanks @slevithan, I'm going to start preparing a new minor release (v4.3.0) following the steps you linked. For reference, here are the changes that will be included (Unicode 12.1.0 and `@babel/runtime-corejs3`): https://github.com/slevithan/xregexp/compare/v4.2.4...master

If all goes well, I'll probably publish to NPM sometime this week.

**Comment by tdjastrzebski** [comment]
If I could advise something: include typescript definitions.

**Comment by josephfrazier** [comment]
Hey @tdjastrzebski, I'm happy to include typescript definitions in a future release, but I don't have enough TS experience to add them myself. Do you know anyone who can help out?

**Comment by tdjastrzebski** [comment]
@josephfrazier: @Bartvds, @jfahrenkrug or @sigo may be able to help.
I think they wrote xregexp typescript defs available at DefinitelyTyped/DefinitelyTyped/tree/master/types/xregexp
It is just that these days it makes way more sense to keep typescript defs with the package.

**Comment by jfahrenkrug** [comment]
@tdjastrzebski I'd be happy to help with including the TS defs in the package. Maybe open a new ticket for it?

**Comment by tdjastrzebski** [comment]
@jfahrenkrug see #284

**Comment by josephfrazier** [comment]
> Thanks @slevithan, I'm going to start preparing a new minor release (v4.3.0) following the steps you linked. For reference, here are the changes that will be included (Unicode 12.1.0 and `@babel/runtime-corejs3`): [v4.2.4...master](https://github.com/slevithan/xregexp/compare/v4.2.4...master)
> 
> If all goes well, I'll probably publish to NPM sometime this week.

Just published v4.3.0: https://www.npmjs.com/package/xregexp/v/4.3.0

> @josephfrazier: @Bartvds, @jfahrenkrug or @sigo may be able to help.
> I think they maintain xregexp typescript defs for ver 3.0 available at [DefinitelyTyped/DefinitelyTyped:types/xregexp@`master`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/xregexp) [](/DefinitelyTyped/DefinitelyTyped/tree/HEAD@{2020-02-06T09:34:31Z}/types/xregexp)
> I think these days it makes way more sense to include typescript defs with the package.

I'll try to take a look at the PRs for this and see if we can get TS defs into the next release, thanks!

**Pull request merged**
