### PR TITLE
Upgrade to Unicode 11

### PR DESCRIPTION
**Pull request by josephfrazier**
For reference/comparison, here's the Unicode 10 upgrade:
https://github.com/slevithan/xregexp/pull/221/

### CODE REVIEW

**Comment by mathiasbynens** [comment]
I’d prefer to wait until Unicode v11 is finalized.

**Comment by josephfrazier** [comment]
Ah, thanks for the info. I don't keep track of the Unicode release schedule, but I noticed you had a the new package out, so I did a blind upgrade. I think it makes sense to wait, though.

**Comment by mathiasbynens** [comment]
Unicode v11 is now released. @josephfrazier, could you please update the dependency to the latest version and run the build script again? We should be good to go then.

**Comment by josephfrazier** [comment]
Done, but it looks like none of the generated files changed :man_shrugging:

**Comment by josephfrazier** [comment]
Thanks for merging! @slevithan, should we release `v4.2.0`?

**Comment by slevithan** [comment]
@josephfrazier, done. v4.2.0 released and published on npm.

**Comment by josephfrazier** [comment]
Sweet, thanks!

**Pull request merged**
